# Generated by Django 4.2.1 on 2023-07-18 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Detail',
        ),
        migrations.AlterModelOptions(
            name='detail',
            options={'ordering': ('name',), 'verbose_name': 'detail', 'verbose_name_plural': 'details'},
        ),
    ]
