# Generated by Django 4.2.1 on 2023-07-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0003_branch_district_person_delete_detail_branch_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='person',
            name='dateofbirth',
            field=models.DateField(auto_now=True, default=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=124),
        ),
    ]
